AWSTemplateFormatVersion: '2010-09-09'

Description: AWS CloudFormation Template for a CHORDS Portal.

#####################################################################
Parameters:
  01KeyName:
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName

  ChordsAdminPw:
    Default: chords_ec_demo
    Description: CHORDS database admin password (this is not the portal admin password). Choose carefully.
    Type: String

  ChordsGuestPw:
    Default: guest
    Description: CHORDS database guest password. Choose carefully.
    Type: String

  ChordsVersion:
    AllowedValues:
      - latest
      - development
    Default: "latest"
    Description: The version of CHORDS to deploy (matches the Docker Hub tags)
    Type: String

  GitBranch:
    AllowedValues:
    - master
    - development
    Default: master
    Description: CHORDS git branch
    Type: String

  GrafanaAdminPw:
    Default: admin
    Description: The password for admin access to Grafana. Once Grafana is initialized with this password, it can only be changed from the Grafana admin web page. Replace this with a secure password.
    Type: String

  ChordsEmailAddress:
    Default: unknown@gmail.com
    Description: An email account that will send CHORDS password reset instructions, Grafana alerts, etc. DO NOT use a personal or business account for this; instead set up an account specifically for CHORDS (e.g. at gmail).
    Type: String

  ChordsEmailPassword:
    Default: unknown
    Description: The password for the email account that will send CHORDS password reset instructions, Grafana alerts, etc. DO NOT use a personal or business account for this; instead set up an account specifically for CHORDS (e.g. at gmail).
    Type: String

  ChordsEmailServer:
    Default: smtp.gmail.com
    Description: The email server that can relay CHORDS password reset instructions, Grafana alerts, etc. You must have an account on this service.
    Type: String

  ChordsEmailPort:
    Default: 587
    Description: The SERVER PORT for the email server that can relay CHORDS password reset instructions, Grafana alerts, etc. You must have an account on this service.
    Type: String

  SecretKeyBase:
    Default: 9a9c4d7e7bed3d85a53bfaaee9cefd338c2ab5fda573cd933dfd3fea4178004425cb50a06df00a0c59a1d353defb9bd3e49fb5f47a791dec7daff95b2a6d080d
    Description: SECRET_KEY_BASE for Rails. This MUST be a randomly generated and 256 bits long.
    Type: String

  DbRetention:
    AllowedValues:
    - INF
    - 4w
    - 12w
    - 24w
    - 52w
    - 104w
    Default: 52w
    Description: Database retention duration (weeks, INF=forever)
    Type: String

  KapacitorEnabled:
    AllowedValues:
    - false
    - true
    Default: false
    Description: Enable kapacitor (WARNING, opens a security hole)
    Type: String

  InstanceType:
    AllowedValues:
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    - t2.xlarge
    - t2.2xlarge
    - m3.medium
    - m3.large
    - m3.xlarge
    - m3.2xlarge
    - c3.large
    - c3.xlarge
    - c3.2xlarge
    - c3.4xlarge
    - c3.8xlarge
    - c4.large
    - c4.xlarge
    - c4.2xlarge
    - c4.4xlarge
    - c4.8xlarge
    - r3.large
    - r3.xlarge
    - r3.2xlarge
    - r3.4xlarge
    - r3.8xlarge
    - i2.xlarge
    - i2.2xlarge
    - i2.4xlarge
    - i2.8xlarge
    - d2.xlarge
    - d2.2xlarge
    - d2.4xlarge
    - d2.8xlarge
    - hi1.4xlarge
    - hs1.8xlarge
    - cr1.8xlarge
    - cc2.8xlarge
    - cg1.4xlarge
    ConstraintDescription: Must be a valid EC2 instance type.
    Default: t2.small
    Description: CHORDS EC2 instance type
    Type: String

  SSHLocation:
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
    Default: 0.0.0.0/0
    Description: ' The IP address range that can be used to SSH to the EC2 instances'
    MaxLength: '18'
    MinLength: '9'
    Type: String

  SecretKeyBase:
    Default: 9a9c4d7e7bed3d85a53bfaaee9cefd338c2ab5fda573cd933dfd3fea4178004425cb50a06df00a0c59a1d353defb9bd3e49fb5f47a791dec7daff95b2a6d080d
    Description: SECRET_KEY_BASE for Rails. This MUST be a randomly generated and 256 bits long.
    Type: String

#####################################################################


Mappings:
  AWSInstanceType2Arch:
    c3.2xlarge:
      Arch: HVM64
    c3.4xlarge:
      Arch: HVM64
    c3.8xlarge:
      Arch: HVM64
    c3.large:
      Arch: HVM64
    c3.xlarge:
      Arch: HVM64
    c4.2xlarge:
      Arch: HVM64
    c4.4xlarge:
      Arch: HVM64
    c4.8xlarge:
      Arch: HVM64
    c4.large:
      Arch: HVM64
    c4.xlarge:
      Arch: HVM64
    cc2.8xlarge:
      Arch: HVM64
    cr1.8xlarge:
      Arch: HVM64
    d2.2xlarge:
      Arch: HVM64
    d2.4xlarge:
      Arch: HVM64
    d2.8xlarge:
      Arch: HVM64
    d2.xlarge:
      Arch: HVM64
    hi1.4xlarge:
      Arch: HVM64
    hs1.8xlarge:
      Arch: HVM64
    i2.2xlarge:
      Arch: HVM64
    i2.4xlarge:
      Arch: HVM64
    i2.8xlarge:
      Arch: HVM64
    i2.xlarge:
      Arch: HVM64
    m3.2xlarge:
      Arch: HVM64
    m3.large:
      Arch: HVM64
    m3.medium:
      Arch: HVM64
    m3.xlarge:
      Arch: HVM64
    r3.2xlarge:
      Arch: HVM64
    r3.4xlarge:
      Arch: HVM64
    r3.8xlarge:
      Arch: HVM64
    r3.large:
      Arch: HVM64
    r3.xlarge:
      Arch: HVM64
    t2.2xlarge:
      Arch: HVM64
    t2.xlarge:
      Arch: HVM64
    t2.large:
      Arch: HVM64
    t2.medium:
      Arch: HVM64
    t2.micro:
      Arch: HVM64
    t2.small:
      Arch: HVM64

  AWSRegionArch2AMI:
    ap-northeast-1:
      HVM64: ami-0997de1cd272740c8
    ap-northeast-2:
      HVM64: ami-014a7f23cc23439fb
    ap-northeast-3:
      HVM64: ami-0b31fb2289bb92d80
    ap-south-1:
      HVM64: ami-0688537d4903f3e1b
    ap-southeast-1:
      HVM64: ami-0332cf924587fe3fc
    ap-southeast-2:
      HVM64: ami-0cd28cf56b0b47a85
    ca-central-1:
      HVM64: ami-0477364f56fb51193
    cn-north-1:
      HVM64: ami-05a64eb2faa4afbe2
    cn-northwest-1:
      HVM64: ami-03bdbb9c6fa74d555
    eu-central-1:
      HVM64: ami-04a99c28815f4a706
    eu-west-1:
      HVM64: ami-01c855eb410b05de7
    eu-west-2:
      HVM64: ami-06d954f8e6d94f918
    eu-west-3:
      HVM64: ami-0d86dbb596eeae4f7
    sa-east-1:
      HVM64: ami-0fd70fc6265d130e1
    us-east-1:
      HVM64: ami-020635c16bf5a82ad
    us-east-2:
      HVM64: ami-0ea8f8e0d477657eb
    us-gov-west-1:
      HVM64: ami-a768f2c6
    us-west-1:
      HVM64: ami-0ff42bc1b2ce9d50d
    us-west-2:
      HVM64: ami-092015093621866d2

#####################################################################
Resources:

  ChordsEIP:
    Properties:
      InstanceId:
        Ref: ChordsServer
    Type: AWS::EC2::EIP

  ChordsServer:
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:
        Timeout: PT30M
    Properties:
      ImageId:
        Fn::FindInMap:
        - AWSRegionArch2AMI
        - Ref: AWS::Region
        - Fn::FindInMap:
          - AWSInstanceType2Arch
          - Ref: InstanceType
          - Arch
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: 01KeyName
      SecurityGroups:
      - Ref: ChordsServerSecurityGroup
      Tags:
      - Key: Name
        Value:
          Ref: AWS::StackName
      - Key: ChordsType
        Value: Portal
      # ChordsServer::Properties::UserData instructs cfn to install and
      # run CHORDS via full_install.
      UserData:
        Fn::Base64:
          Fn::Join:
          - ''
          - - '#!/bin/bash -xe

              '
            - 'yum update -y aws-cfn-bootstrap

              '
            - '/opt/aws/bin/cfn-init -v '
            - '         --stack '
            - Ref: AWS::StackId
            - '         --resource ChordsServer '
            - '         --configsets full_install '
            - '         --region '
            - Ref: AWS::Region
            - '

              '
            - '/opt/aws/bin/cfn-signal -e $? '
            - '         --stack '
            - Ref: AWS::StackId
            - '         --resource ChordsServer '
            - '         --region '
            - Ref: AWS::Region
            - '

              '
    Metadata:
      AWS::CloudFormation::Init:
        # configSets specifies the order that cfn_init runs
        # the other AWS::CloudFormation::Init: types.
        configSets:
          full_install:
          - install_cfn
          - sys_update
          - yum_extras
          - install_docker
          - install_docker_compose
          - chords_setup
          - chords_config
          - docker_pull
          - chords_service

        # configure cfn.
        install_cfn:
          files:
            /etc/cfn/cfn-hup.conf:
              content:
                Fn::Join:
                - ''
                - - '[main]

                    '
                  - stack=
                  - Ref: AWS::StackId
                  - '

                    '
                  - region=
                  - Ref: AWS::Region
                  - '

                    '
              group: root
              mode: '000400'
              owner: root
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content:
                Fn::Join:
                - ''
                - - '[cfn-auto-reloader-hook]

                    '
                  - 'triggers=post.update

                    '
                  - 'path=Resources.ChordsServer.Metadata.AWS::CloudFormation::Init

                    '
                  - 'action=/opt/aws/bin/cfn-init -v '
                  - '         --stack '
                  - Ref: AWS::StackName
                  - '         --resource ChordsServer '
                  - '         --configsets full_install '
                  - '         --region '
                  - Ref: AWS::Region
                  - '

                    '
                  - 'runas=root

                    '
          services:
            sysvinit:
              cfn-hup:
                enabled: 'true'
                ensureRunning: 'true'
                files:
                - /etc/cfn/cfn-hup.conf
                - /etc/cfn/hooks.d/cfn-auto-reloader.conf

        # Perform a yum update for the system.
        sys_update:
          commands:
            01_update:
              command: yum update -y

        # Install some useful packages.
        yum_extras:
          packages:
            yum:
              emacs: []
              sysstat: []
              git: []
              python2-pip: []

        # Install docker as a service.
        install_docker:
          packages:
            yum:
              docker: []
          commands:
            01_enable:
              command: "systemctl enable docker"
            02_start:
              command: "systemctl start docker"

        # Install docker-compose
        install_docker_compose:
          commands:
            # Install docker-compose.
            01_get_docker_compose:
              command: "curl -L https://github.com/docker/compose/releases/download/1.10.0/docker-compose-`uname -s`-`uname -m` > /bin/docker-compose && chmod +x /bin/docker-compose"

        # Set up CHORDS
        chords_setup:
          commands:
            00_python_pip:
              command: "pip install sh"
            01_var_lib_chords:
              command: "mkdir -p /var/lib/chords"
            02_get_chords_control:
              command: !Sub "curl -L https://raw.github.com/earthcubeprojects-chords/chords/${GitBranch}/chords_control > /var/lib/chords/chords_control"
            03_get_docker_compose_yml:
              command: !Sub "curl -L https://raw.github.com/earthcubeprojects-chords/chords/${GitBranch}/docker-compose.yml > /var/lib/chords/docker-compose.yml"

        # Create the CHORDS and docker-compose configuration files.
        chords_config:
          files:
            # Create the basic configuration in .env:
            /var/lib/chords/.env:
              content: !Sub |
                CHORDS_ADMIN_PW=${ChordsAdminPw}
                CHORDS_GUEST_PW=${ChordsGuestPw}
                CHORDS_EMAIL_ADDRESS=${ChordsEmailAddress}
                CHORDS_EMAIL_PASSWORD=${ChordsEmailPassword}
                CHORDS_EMAIL_SERVER=${ChordsEmailServer}
                CHORDS_EMAIL_PORT=${ChordsEmailPort}
                GRAFANA_ADMIN_PW=${GrafanaAdminPw}
                GIT_BRANCH=${GitBranch}
                DOCKER_TAG=${ChordsVersion}
                RAILS_ENV=production
                DB_RETENTION=${DbRetention}
                SECRET_KEY_BASE=${SecretKeyBase}
                KAPACITOR_ENABLED=${KapacitorEnabled}
          commands:
            # Create chords.yml from .env. The .env file will also be updated.
            01_create_chords_yml:
              command: "cd /var/lib/chords && python chords_control -b"

        # Install docker-compose.yml and get the CHORDS images.
        docker_pull:
          commands:
            # Pull the CHORDS images.
            02_docker_pull:
              command: "cd /var/lib/chords && /bin/docker-compose pull"

        # Install and enable the chords service
        chords_service:
          files:
            /var/lib/chords/chords.service:
              content: |
                [Unit]
                Description=CHORDS Portal
                After=docker.service
                Requires=docker.service

                [Service]
                Type=simple
                WorkingDirectory=/var/lib/chords
                ExecStartPre=/bin/docker-compose -p chords down
                ExecStart=/bin/docker-compose    -p chords up
                ExecStop=/bin/docker-compose     -p chords down
                Restart=always
                RestartSec=60

                [Install]
                WantedBy=multi-user.target
              group: root
              mode: '000755'
              owner: root

          commands:
            # Enable the chords service
            01_enable:
              command: "systemctl enable /var/lib/chords/chords.service"
            # Start the chords service
            02_startchords:
              command: "systemctl start chords"

  ChordsServerSecurityGroup:
    Properties:
      GroupDescription: Enable HTTP and SSH access
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: '80'
        IpProtocol: tcp
        ToPort: '80'
      - CidrIp:
          Ref: SSHLocation
        FromPort: '22'
        IpProtocol: tcp
        ToPort: '22'
      - CidrIp: 0.0.0.0/0
        FromPort: '25'
        IpProtocol: tcp
        ToPort: '25'
      - CidrIp: 0.0.0.0/0
        FromPort: '3000'
        IpProtocol: tcp
        ToPort: '3000'
      - CidrIp: 0.0.0.0/0
        FromPort: '9092'
        IpProtocol: tcp
        ToPort: '9092'
    Type: AWS::EC2::SecurityGroup

#####################################################################
Outputs:
  WebsiteURL:
    Description: URL for newly created CHORDS Portal
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt:
          - ChordsServer
          - PublicDnsName
        - ''

